<?php
/**
 * @file
 * My hooks
 */

/**
 * Implements hook_menu().
 */
function entitydemo_menu() {
  $items = [];
  $items['demo'] = [
    'title' => 'Entity Demos',
    'description' => 'List of entity demo provided by this module .',
    'access callback' => TRUE,
    'page callback' => 'entitydemo_demos',
    'menu_name' => 'navigation',
    'file' => 'includes/entitydemo.demos.inc',
  ];
  $items['demo/1'] = [
    'title' => 'Entity load demo',
    'description' => 'Demonstrates API functions that make it easier to work with exsiting entities.',
    'access callback' => TRUE,
    'page callback' => 'entitydemo_page1',
    'file' => 'includes/entitydemo.demo1.inc',

  ];

  $items['demo/2'] = [
    'title' => 'EntityFieldQuery',
    'description' => 'Demonstrates API EntityFieldQuery',
    'access callback' => TRUE,
    'page callback' => 'entitydemo_page2',
    'file' => 'includes/entitydemo.demo2.inc'
  ];

  return $items;

}

/**
 * Implements hook_node_view().
 */
function entitydemo_node_view($node, $view_mode, $langcode) {
  if ($view_mode=='full') {
    //dpm($node->field_article_subtitle[LANGUAGE_NONE][0]['safe_value']);
    $node_wrapper = entity_metadata_wrapper('node',$node);

    //value from metadata wrapper
    $field_article_subtitle = $node_wrapper->field_article_subtitle->value();
    dpm($field_article_subtitle);
    $node_wrapper->field_article_subtitle->set('my changed article subtitle');
    //save field to database
    $node_wrapper->save();
    dpm($node_wrapper->field_article_subtitle->value());
    dpm($node_wrapper->get('field_article_subtitle'));


    dpm($node_wrapper->author->mail->value(),'Email adress of the author');

    dpm($node_wrapper->getPropertyInfo());

    //get iterate tags
    foreach ($node_wrapper->field_tags->getIterator() as $tag) {
      dpm($tag->getPropertyInfo());
      dpm($tag->label(),'Tag label: ');
      dpm($tag->name->value(),'Tag name: ');
    }
  }

}